"""Resolve and register custom Wan model paths."""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from engine_paths import resolve_engine

DEFAULT_GGUF = "Wan2.1-T2V-1.3B-Q4_K_M.gguf"
DEFAULT_T5 = "umt5-xxl-enc-fp8_e4m3fn.safetensors"
DEFAULT_VAE = "Wan2_1_VAE_bf16.safetensors"


@dataclass
class ModelPaths:
    gguf_name: str
    t5_name: str
    vae_name: str
    gguf_file: Path
    t5_file: Path
    vae_file: Path
    extra_model_paths_yaml: Path | None

    def patch_workflow(self, workflow: dict) -> dict:
        for node in workflow.values():
            ct = node.get("class_type")
            ins = node.get("inputs", {})
            if ct == "WanVideoModelLoader":
                ins["model"] = self.gguf_name
            elif ct == "LoadWanVideoT5TextEncoder":
                ins["model_name"] = self.t5_name
            elif ct == "WanVideoVAELoader":
                ins["model_name"] = self.vae_name
        return workflow


def _resolve_one(
    path_env: str,
    name_env: str,
    default_name: str,
    subdir: str,
    models_root: Path,
) -> tuple[str, Path, Path | None]:
    """Return (comfy_list_name, absolute_file, extra_search_dir or None)."""
    if path_env:
        p = Path(path_env).expanduser().resolve()
        return p.name, p, p.parent
    name = name_env or default_name
    p = Path(name)
    if p.is_absolute():
        return p.name, p.resolve(), p.parent
    file_path = (models_root / subdir / name).resolve()
    return name, file_path, None


def load_model_paths(engine_root: Path, service_root: Path) -> ModelPaths:
    models_root = os.environ.get("MODELS_ROOT", "").strip()
    if models_root:
        root = Path(models_root).expanduser().resolve()
    else:
        root = resolve_engine(engine_root)[2].resolve()

    gguf_name, gguf_file, gguf_extra = _resolve_one(
        os.environ.get("GGUF_PATH", ""),
        os.environ.get("GGUF_MODEL", ""),
        DEFAULT_GGUF,
        "diffusion_models",
        root,
    )
    t5_name, t5_file, t5_extra = _resolve_one(
        os.environ.get("T5_PATH", ""),
        os.environ.get("T5_MODEL", ""),
        DEFAULT_T5,
        "text_encoders",
        root,
    )
    vae_name, vae_file, vae_extra = _resolve_one(
        os.environ.get("VAE_PATH", ""),
        os.environ.get("VAE_MODEL", ""),
        DEFAULT_VAE,
        "vae",
        root,
    )

    _er, comfy_dir, models_dir = resolve_engine(engine_root)
    default_root = models_dir.resolve()
    need_extra = root != default_root or any((gguf_extra, t5_extra, vae_extra))

    extra_yaml: Path | None = None
    if need_extra:
        runtime = service_root / ".runtime"
        runtime.mkdir(parents=True, exist_ok=True)
        extra_yaml = runtime / "extra_model_paths.yaml"
        comfy_base = comfy_dir.resolve()

        def _norm(p: Path) -> str:
            return str(p.resolve()).replace("\\", "/")

        def _yaml_path(extra_dir: Path | None, subdir: str) -> str:
            if extra_dir is not None:
                return _norm(extra_dir)
            return _norm(root / subdir)

        lines = [
            "# Auto-generated by video-service — do not edit",
            "comfyui:",
            f"  base_path: {_norm(comfy_base)}/",
            "  is_default: true",
            "  diffusion_models: |",
            f"    {_yaml_path(gguf_extra, 'diffusion_models')}",
            f"    {_norm(default_root / 'diffusion_models')}",
            "  text_encoders: |",
            f"    {_yaml_path(t5_extra, 'text_encoders')}",
            f"    {_norm(default_root / 'text_encoders')}",
            "  vae: |",
            f"    {_yaml_path(vae_extra, 'vae')}",
            f"    {_norm(default_root / 'vae')}",
        ]
        extra_yaml.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return ModelPaths(
        gguf_name=gguf_name,
        t5_name=t5_name,
        vae_name=vae_name,
        gguf_file=gguf_file,
        t5_file=t5_file,
        vae_file=vae_file,
        extra_model_paths_yaml=extra_yaml,
    )
